#!/usr/bin/env python
import re
lyrics = '12 drummers drumming, 11 pipers piping, 10 lords a leaping, 9 ladies dancing, 8 maids a milking, 7 swans a swimming, 6 geese a laying, 5 golden rinds, 4 calling birds, 3 french rens, 2 turtle doves, and 1 partridge in a pear tree'
print(' digit space words '.center(75,'-'))
p1 = re.compile(r'\d+\s\w+')
print(p1)
print(p1.findall(lyrics))
print(' digit words starting in G '.center(75,'-'))
p1 = re.compile(r'\d+\sg\w+')
print(p1)
print(p1.findall(lyrics))
print(' double digit w/ words '.center(75,'-'))
p1 = re.compile(r'\d{2}\s\w+')
print(p1)
print(p1.findall(lyrics))
print(' digit w/ 5 chars words '.center(75,'-'))
p1 = re.compile(r'\d+\s\w{5}\s')
print(p1)
print(p1.findall(lyrics))
print(' words before comma '.center(75,'-'))
p1 = re.compile(r'\s(\w+),')
print(p1)
print(p1.findall(lyrics))
print(' words ending w/ ING '.center(75,'-'))
p1 = re.compile(r'\s(\w+ing)')
print(p1)
print(p1.findall(lyrics))
print(' words containing vowels '.center(75,'-'))
p1 = re.compile(r'(\w+[aeiouAEIOU]+\w*)\s?')
print(p1)
print(p1.findall(lyrics))
print(' words containing double vowels '.center(75,'-'))
p1 = re.compile(r'(\w+[aeiouAEIOU]{2}\w*)\s?')
print(p1)
print(p1.findall(lyrics))


